// Mock Teamflect data that matches the exact API structure
// This allows UI testing even when API is not accessible

import type { Goal, Task, Feedback, Recognition, User, Review } from '@/types/teamflect';

export const mockUsers: User[] = [
  {
    oid: '1a2b3c4d-5e6f-7g8h-9i0j-k1l2m3n4o5p6',
    displayName: 'John Smith',
    userPrincipalName: 'john.smith@company.com',
    mail: 'john.smith@company.com',
    department: 'Engineering',
    jobTitle: 'Senior Developer',
  },
  {
    oid: '2b3c4d5e-6f7g-8h9i-0j1k-l2m3n4o5p6q7',
    displayName: 'Sarah Johnson',
    userPrincipalName: 'sarah.johnson@company.com',
    mail: 'sarah.johnson@company.com',
    department: 'Product',
    jobTitle: 'Product Manager',
  },
  {
    oid: '3c4d5e6f-7g8h-9i0j-1k2l-m3n4o5p6q7r8',
    displayName: 'Michael Chen',
    userPrincipalName: 'michael.chen@company.com',
    mail: 'michael.chen@company.com',
    department: 'Engineering',
    jobTitle: 'Tech Lead',
  },
  {
    oid: '4d5e6f7g-8h9i-0j1k-2l3m-n4o5p6q7r8s9',
    displayName: 'Emily Davis',
    userPrincipalName: 'emily.davis@company.com',
    mail: 'emily.davis@company.com',
    department: 'Design',
    jobTitle: 'UX Designer',
  },
  {
    oid: '5e6f7g8h-9i0j-1k2l-3m4n-o5p6q7r8s9t0',
    displayName: 'David Wilson',
    userPrincipalName: 'david.wilson@company.com',
    mail: 'david.wilson@company.com',
    department: 'Sales',
    jobTitle: 'Sales Director',
  },
];

export const mockGoals: Goal[] = [
  {
    id: 'goal-1',
    title: 'Launch New Product Feature',
    description: 'Complete development and launch of the new analytics dashboard feature for Q4',
    createdBy: mockUsers[0],
    startDate: '2025-01-01',
    dueDate: '2025-03-31',
    owners: [mockUsers[0], mockUsers[2]],
    status: 'on-track',
    progress: 65,
    labels: ['Product', 'Engineering'],
    keyResults: [
      {
        id: 'kr-1',
        title: 'Complete UI Design',
        targetValue: 100,
        currentValue: 85,
        unit: '%',
        progress: 85,
      },
      {
        id: 'kr-2',
        title: 'Backend API Development',
        targetValue: 100,
        currentValue: 75,
        unit: '%',
        progress: 75,
      },
    ],
  },
  {
    id: 'goal-2',
    title: 'Improve Customer Satisfaction Score',
    description: 'Increase NPS score from 45 to 60 through improved customer support and product quality',
    createdBy: mockUsers[1],
    startDate: '2025-01-01',
    dueDate: '2025-06-30',
    owners: [mockUsers[1], mockUsers[4]],
    status: 'at-risk',
    progress: 35,
    labels: ['Customer Success', 'Product'],
    keyResults: [
      {
        id: 'kr-3',
        title: 'Reduce Response Time',
        targetValue: 2,
        currentValue: 4,
        unit: 'hours',
        progress: 50,
      },
    ],
  },
  {
    id: 'goal-3',
    title: 'Scale Engineering Team',
    description: 'Hire 10 senior engineers to support product expansion',
    createdBy: mockUsers[2],
    startDate: '2025-02-01',
    dueDate: '2025-12-31',
    owners: [mockUsers[2]],
    status: 'on-track',
    progress: 40,
    labels: ['Hiring', 'Engineering'],
  },
  {
    id: 'goal-4',
    title: 'Revenue Growth Target',
    description: 'Achieve $10M ARR by end of year',
    createdBy: mockUsers[4],
    startDate: '2025-01-01',
    dueDate: '2025-12-31',
    owners: [mockUsers[4]],
    status: 'on-track',
    progress: 58,
    labels: ['Revenue', 'Sales'],
  },
  {
    id: 'goal-5',
    title: 'Improve System Performance',
    description: 'Reduce page load time by 40% across all pages',
    createdBy: mockUsers[0],
    startDate: '2025-03-01',
    dueDate: '2025-05-31',
    owners: [mockUsers[0], mockUsers[2]],
    status: 'off-track',
    progress: 20,
    labels: ['Performance', 'Engineering'],
  },
  {
    id: 'goal-6',
    title: 'Complete Design System v2',
    description: 'Launch comprehensive design system with component library',
    createdBy: mockUsers[3],
    startDate: '2025-02-01',
    dueDate: '2025-04-30',
    owners: [mockUsers[3]],
    status: 'completed',
    progress: 100,
    labels: ['Design', 'Product'],
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Review pull request #234',
    description: 'Review and approve the new authentication flow implementation',
    assignedTo: [mockUsers[2]],
    dueDate: '2025-11-05',
    status: 'in-progress',
    priority: 'high',
    createdBy: mockUsers[0],
    createdAt: '2025-11-01',
  },
  {
    id: 'task-2',
    title: 'Update product documentation',
    description: 'Add documentation for new API endpoints',
    assignedTo: [mockUsers[1]],
    dueDate: '2025-11-10',
    status: 'todo',
    priority: 'medium',
    createdBy: mockUsers[1],
    createdAt: '2025-11-02',
  },
  {
    id: 'task-3',
    title: 'Fix critical bug in payment flow',
    description: 'Users reporting issues with credit card processing',
    assignedTo: [mockUsers[0]],
    dueDate: '2025-11-04',
    status: 'in-progress',
    priority: 'high',
    createdBy: mockUsers[2],
    createdAt: '2025-11-03',
  },
  {
    id: 'task-4',
    title: 'Design new onboarding flow',
    description: 'Create mockups for improved user onboarding experience',
    assignedTo: [mockUsers[3]],
    dueDate: '2025-11-08',
    status: 'completed',
    priority: 'medium',
    createdBy: mockUsers[3],
    createdAt: '2025-10-25',
  },
  {
    id: 'task-5',
    title: 'Prepare Q4 sales presentation',
    description: 'Create slide deck for quarterly business review',
    assignedTo: [mockUsers[4]],
    dueDate: '2025-10-30',
    status: 'completed',
    priority: 'low',
    createdBy: mockUsers[4],
    createdAt: '2025-10-20',
  },
  {
    id: 'task-6',
    title: 'Refactor authentication module',
    description: 'Improve code quality and add unit tests',
    assignedTo: [mockUsers[0], mockUsers[2]],
    dueDate: '2025-11-15',
    status: 'todo',
    priority: 'medium',
    createdBy: mockUsers[2],
    createdAt: '2025-11-01',
  },
];

export const mockFeedback: Feedback[] = [
  {
    id: 'feedback-1',
    sender: mockUsers[1],
    recipient: mockUsers[0],
    message: 'Great job on the new feature implementation! The code quality is excellent and the performance improvements are noticeable.',
    type: 'praise',
    createdAt: '2025-11-02',
    isAnonymous: false,
  },
  {
    id: 'feedback-2',
    sender: mockUsers[2],
    recipient: mockUsers[3],
    message: 'The design mockups look amazing! However, consider adding more spacing between elements for better readability on mobile devices.',
    type: 'constructive',
    createdAt: '2025-11-01',
    isAnonymous: false,
  },
  {
    id: 'feedback-3',
    sender: mockUsers[4],
    recipient: mockUsers[1],
    message: 'Could you help prioritize the customer feedback items for next sprint? Your insights would be valuable.',
    type: 'request',
    createdAt: '2025-10-31',
    isAnonymous: false,
  },
  {
    id: 'feedback-4',
    sender: mockUsers[0],
    recipient: mockUsers[2],
    message: 'Thank you for the thorough code review! Your suggestions significantly improved the architecture.',
    type: 'praise',
    createdAt: '2025-10-30',
    isAnonymous: false,
  },
];

export const mockRecognitions: Recognition[] = [
  {
    id: 'recognition-1',
    sender: mockUsers[2],
    recipient: mockUsers[0],
    title: '🏆 Excellence in Engineering',
    message: 'John consistently delivers high-quality code and mentors junior developers. His dedication to best practices has elevated our entire engineering team.',
    createdAt: '2025-11-02',
    likes: 12,
  },
  {
    id: 'recognition-2',
    sender: mockUsers[0],
    recipient: mockUsers[1],
    title: '⭐ Product Leadership',
    message: 'Sarah\'s product vision and user-centric approach have been instrumental in our recent successes. Her ability to balance stakeholder needs is exceptional.',
    createdAt: '2025-11-01',
    likes: 15,
  },
  {
    id: 'recognition-3',
    sender: mockUsers[1],
    recipient: mockUsers[3],
    title: '🎨 Design Innovation',
    message: 'Emily\'s design work on the new interface is outstanding! Users are loving the improved experience.',
    createdAt: '2025-10-29',
    likes: 18,
  },
  {
    id: 'recognition-4',
    sender: mockUsers[4],
    recipient: mockUsers[2],
    title: '🚀 Technical Leadership',
    message: 'Michael\'s technical guidance helped us scale our infrastructure to handle 10x traffic. Amazing work!',
    createdAt: '2025-10-28',
    likes: 20,
  },
];

export const mockReviews: Review[] = [
  {
    id: 'review-1',
    reviewee: mockUsers[0],
    reviewer: mockUsers[2],
    period: 'Q3 2025',
    status: 'completed',
    rating: 4.5,
    competencies: [
      { id: 'comp-1', name: 'Technical Skills', rating: 5, comments: 'Excellent' },
      { id: 'comp-2', name: 'Communication', rating: 4, comments: 'Very good' },
      { id: 'comp-3', name: 'Leadership', rating: 4.5, comments: 'Strong leader' },
    ],
    createdAt: '2025-10-01',
    completedAt: '2025-10-15',
  },
  {
    id: 'review-2',
    reviewee: mockUsers[1],
    reviewer: mockUsers[4],
    period: 'Q3 2025',
    status: 'in-progress',
    rating: undefined,
    createdAt: '2025-10-01',
  },
];
